// ─── CONJUGAISON DATA ───────────────────────────────────────────────────────
// Structure: verb → tense → [yo, tú, él, nosotros, vosotros, ellos]
//
// Temps couverts :
//  presente             → présent de l'indicatif
//  indefinido           → prétérit indéfini
//  imperfecto           → imparfait de l'indicatif
//  perfecto             → prétérit parfait composé (he/has... + participio)
//  pluscuamperfecto     → plus-que-parfait (había/habías... + participio)
//  futuro               → futur simple
//  condicional          → conditionnel présent
//  subjuntivo_presente  → subjonctif présent
//  subjuntivo_imperfecto→ subjonctif imparfait (-ra)
//  imperativo           → impératif affirmatif (yo = '—')
//  imperativo_neg       → impératif négatif    (yo = '—')

const PRONOUNS = ['yo', 'tú', 'él/ella', 'nosotros', 'vosotros', 'ellos/ellas'];

const TENSE_LABELS = {
  presente:              'présent',
  indefinido:            'prétérit indéfini',
  imperfecto:            'imparfait',
  perfecto:              'prétérit parfait composé',
  pluscuamperfecto:      'plus-que-parfait',
  futuro:                'futur simple',
  condicional:           'conditionnel',
  subjuntivo_presente:   'subjonctif présent',
  subjuntivo_imperfecto: 'subjonctif imparfait',
  subjuntivo_pasado:     'subjonctif passé',
  imperativo:            'impératif',
  imperativo_neg:        'impératif négatif',
};

// Auxiliaire haber au subjonctif présent
const HABER_SUBJ = ['haya','hayas','haya','hayamos','hayáis','hayan'];

const VERBS = {

  // ═══ RÉGULIERS -AR ═══════════════════════════════════════════════════════

  hablar: {
    label: 'parler',
    presente:              ['hablo','hablas','habla','hablamos','habláis','hablan'],
    indefinido:            ['hablé','hablaste','habló','hablamos','hablasteis','hablaron'],
    imperfecto:            ['hablaba','hablabas','hablaba','hablábamos','hablabais','hablaban'],
    perfecto:              ['he hablado','has hablado','ha hablado','hemos hablado','habéis hablado','han hablado'],
    pluscuamperfecto:      ['había hablado','habías hablado','había hablado','habíamos hablado','habíais hablado','habían hablado'],
    futuro:                ['hablaré','hablarás','hablará','hablaremos','hablaréis','hablarán'],
    condicional:           ['hablaría','hablarías','hablaría','hablaríamos','hablaríais','hablarían'],
    subjuntivo_presente:   ['hable','hables','hable','hablemos','habléis','hablen'],
    subjuntivo_imperfecto: ['hablara','hablaras','hablara','habláramos','hablarais','hablaran'],
    imperativo:            ['—','habla','hable','hablemos','hablad','hablen'],
    imperativo_neg:        ['—','no hables','no hable','no hablemos','no habléis','no hablen'],
  },
  trabajar: {
    label: 'travailler',
    presente:              ['trabajo','trabajas','trabaja','trabajamos','trabajáis','trabajan'],
    indefinido:            ['trabajé','trabajaste','trabajó','trabajamos','trabajasteis','trabajaron'],
    imperfecto:            ['trabajaba','trabajabas','trabajaba','trabajábamos','trabajabais','trabajaban'],
    perfecto:              ['he trabajado','has trabajado','ha trabajado','hemos trabajado','habéis trabajado','han trabajado'],
    pluscuamperfecto:      ['había trabajado','habías trabajado','había trabajado','habíamos trabajado','habíais trabajado','habían trabajado'],
    futuro:                ['trabajaré','trabajarás','trabajará','trabajaremos','trabajaréis','trabajarán'],
    condicional:           ['trabajaría','trabajarías','trabajaría','trabajaríamos','trabajaríais','trabajarían'],
    subjuntivo_presente:   ['trabaje','trabajes','trabaje','trabajemos','trabajéis','trabajen'],
    subjuntivo_imperfecto: ['trabajara','trabajaras','trabajara','trabajáramos','trabajarais','trabajaran'],
    imperativo:            ['—','trabaja','trabaje','trabajemos','trabajad','trabajen'],
    imperativo_neg:        ['—','no trabajes','no trabaje','no trabajemos','no trabajéis','no trabajen'],
  },
  escuchar: {
    label: 'écouter',
    presente:              ['escucho','escuchas','escucha','escuchamos','escucháis','escuchan'],
    indefinido:            ['escuché','escuchaste','escuchó','escuchamos','escuchasteis','escucharon'],
    imperfecto:            ['escuchaba','escuchabas','escuchaba','escuchábamos','escuchabais','escuchaban'],
    perfecto:              ['he escuchado','has escuchado','ha escuchado','hemos escuchado','habéis escuchado','han escuchado'],
    pluscuamperfecto:      ['había escuchado','habías escuchado','había escuchado','habíamos escuchado','habíais escuchado','habían escuchado'],
    futuro:                ['escucharé','escucharás','escuchará','escucharemos','escucharéis','escucharán'],
    condicional:           ['escucharía','escucharías','escucharía','escucharíamos','escucharíais','escucharían'],
    subjuntivo_presente:   ['escuche','escuches','escuche','escuchemos','escuchéis','escuchen'],
    subjuntivo_imperfecto: ['escuchara','escucharas','escuchara','escucháramos','escucharais','escucharan'],
    imperativo:            ['—','escucha','escuche','escuchemos','escuchad','escuchen'],
    imperativo_neg:        ['—','no escuches','no escuche','no escuchemos','no escuchéis','no escuchen'],
  },
  caminar: {
    label: 'marcher',
    presente:              ['camino','caminas','camina','caminamos','camináis','caminan'],
    indefinido:            ['caminé','caminaste','caminó','caminamos','caminasteis','caminaron'],
    imperfecto:            ['caminaba','caminabas','caminaba','caminábamos','caminabais','caminaban'],
    perfecto:              ['he caminado','has caminado','ha caminado','hemos caminado','habéis caminado','han caminado'],
    pluscuamperfecto:      ['había caminado','habías caminado','había caminado','habíamos caminado','habíais caminado','habían caminado'],
    futuro:                ['caminaré','caminarás','caminará','caminaremos','caminaréis','caminarán'],
    condicional:           ['caminaría','caminarías','caminaría','caminaríamos','caminaríais','caminarían'],
    subjuntivo_presente:   ['camine','camines','camine','caminemos','caminéis','caminen'],
    subjuntivo_imperfecto: ['caminara','caminaras','caminara','camináramos','caminarais','caminaran'],
    imperativo:            ['—','camina','camine','caminemos','caminad','caminen'],
    imperativo_neg:        ['—','no camines','no camine','no caminemos','no caminéis','no caminen'],
  },
  comprar: {
    label: 'acheter',
    presente:              ['compro','compras','compra','compramos','compráis','compran'],
    indefinido:            ['compré','compraste','compró','compramos','comprasteis','compraron'],
    imperfecto:            ['compraba','comprabas','compraba','comprábamos','comprabais','compraban'],
    perfecto:              ['he comprado','has comprado','ha comprado','hemos comprado','habéis comprado','han comprado'],
    pluscuamperfecto:      ['había comprado','habías comprado','había comprado','habíamos comprado','habíais comprado','habían comprado'],
    futuro:                ['compraré','comprarás','comprará','compraremos','compraréis','comprarán'],
    condicional:           ['compraría','comprarías','compraría','compraríamos','compraríais','comprarían'],
    subjuntivo_presente:   ['compre','compres','compre','compremos','compréis','compren'],
    subjuntivo_imperfecto: ['comprara','compraras','comprara','compráramos','comprarais','compraran'],
    imperativo:            ['—','compra','compre','compremos','comprad','compren'],
    imperativo_neg:        ['—','no compres','no compre','no compremos','no compréis','no compren'],
  },
  llevar: {
    label: 'porter / emmener',
    presente:              ['llevo','llevas','lleva','llevamos','lleváis','llevan'],
    indefinido:            ['llevé','llevaste','llevó','llevamos','llevasteis','llevaron'],
    imperfecto:            ['llevaba','llevabas','llevaba','llevábamos','llevabais','llevaban'],
    perfecto:              ['he llevado','has llevado','ha llevado','hemos llevado','habéis llevado','han llevado'],
    pluscuamperfecto:      ['había llevado','habías llevado','había llevado','habíamos llevado','habíais llevado','habían llevado'],
    futuro:                ['llevaré','llevarás','llevará','llevaremos','llevaréis','llevarán'],
    condicional:           ['llevaría','llevarías','llevaría','llevaríamos','llevaríais','llevarían'],
    subjuntivo_presente:   ['lleve','lleves','lleve','llevemos','llevéis','lleven'],
    subjuntivo_imperfecto: ['llevara','llevaras','llevara','lleváramos','llevarais','llevaran'],
    imperativo:            ['—','lleva','lleve','llevemos','llevad','lleven'],
    imperativo_neg:        ['—','no lleves','no lleve','no llevemos','no llevéis','no lleven'],
  },

  // ═══ RÉGULIERS -ER ═══════════════════════════════════════════════════════

  comer: {
    label: 'manger',
    presente:              ['como','comes','come','comemos','coméis','comen'],
    indefinido:            ['comí','comiste','comió','comimos','comisteis','comieron'],
    imperfecto:            ['comía','comías','comía','comíamos','comíais','comían'],
    perfecto:              ['he comido','has comido','ha comido','hemos comido','habéis comido','han comido'],
    pluscuamperfecto:      ['había comido','habías comido','había comido','habíamos comido','habíais comido','habían comido'],
    futuro:                ['comeré','comerás','comerá','comeremos','comeréis','comerán'],
    condicional:           ['comería','comerías','comería','comeríamos','comeríais','comerían'],
    subjuntivo_presente:   ['coma','comas','coma','comamos','comáis','coman'],
    subjuntivo_imperfecto: ['comiera','comieras','comiera','comiéramos','comierais','comieran'],
    imperativo:            ['—','come','coma','comamos','comed','coman'],
    imperativo_neg:        ['—','no comas','no coma','no comamos','no comáis','no coman'],
  },
  beber: {
    label: 'boire',
    presente:              ['bebo','bebes','bebe','bebemos','bebéis','beben'],
    indefinido:            ['bebí','bebiste','bebió','bebimos','bebisteis','bebieron'],
    imperfecto:            ['bebía','bebías','bebía','bebíamos','bebíais','bebían'],
    perfecto:              ['he bebido','has bebido','ha bebido','hemos bebido','habéis bebido','han bebido'],
    pluscuamperfecto:      ['había bebido','habías bebido','había bebido','habíamos bebido','habíais bebido','habían bebido'],
    futuro:                ['beberé','beberás','beberá','beberemos','beberéis','beberán'],
    condicional:           ['bebería','beberías','bebería','beberíamos','beberíais','beberían'],
    subjuntivo_presente:   ['beba','bebas','beba','bebamos','bebáis','beban'],
    subjuntivo_imperfecto: ['bebiera','bebieras','bebiera','bebiéramos','bebierais','bebieran'],
    imperativo:            ['—','bebe','beba','bebamos','bebed','beban'],
    imperativo_neg:        ['—','no bebas','no beba','no bebamos','no bebáis','no beban'],
  },
  correr: {
    label: 'courir',
    presente:              ['corro','corres','corre','corremos','corréis','corren'],
    indefinido:            ['corrí','corriste','corrió','corrimos','corristeis','corrieron'],
    imperfecto:            ['corría','corrías','corría','corríamos','corríais','corrían'],
    perfecto:              ['he corrido','has corrido','ha corrido','hemos corrido','habéis corrido','han corrido'],
    pluscuamperfecto:      ['había corrido','habías corrido','había corrido','habíamos corrido','habíais corrido','habían corrido'],
    futuro:                ['correré','correrás','correrá','correremos','correréis','correrán'],
    condicional:           ['correría','correrías','correría','correríamos','correríais','correrían'],
    subjuntivo_presente:   ['corra','corras','corra','corramos','corráis','corran'],
    subjuntivo_imperfecto: ['corriera','corrieras','corriera','corriéramos','corrierais','corrieran'],
    imperativo:            ['—','corre','corra','corramos','corred','corran'],
    imperativo_neg:        ['—','no corras','no corra','no corramos','no corráis','no corran'],
  },
  conocer: {
    label: 'connaître',
    presente:              ['conozco','conoces','conoce','conocemos','conocéis','conocen'],
    indefinido:            ['conocí','conociste','conoció','conocimos','conocisteis','conocieron'],
    imperfecto:            ['conocía','conocías','conocía','conocíamos','conocíais','conocían'],
    perfecto:              ['he conocido','has conocido','ha conocido','hemos conocido','habéis conocido','han conocido'],
    pluscuamperfecto:      ['había conocido','habías conocido','había conocido','habíamos conocido','habíais conocido','habían conocido'],
    futuro:                ['conoceré','conocerás','conocerá','conoceremos','conoceréis','conocerán'],
    condicional:           ['conocería','conocerías','conocería','conoceríamos','conoceríais','conocerían'],
    subjuntivo_presente:   ['conozca','conozcas','conozca','conozcamos','conozcáis','conozcan'],
    subjuntivo_imperfecto: ['conociera','conocieras','conociera','conociéramos','conocierais','conocieran'],
    imperativo:            ['—','conoce','conozca','conozcamos','conoced','conozcan'],
    imperativo_neg:        ['—','no conozcas','no conozca','no conozcamos','no conozcáis','no conozcan'],
  },
  leer: {
    label: 'lire',
    presente:              ['leo','lees','lee','leemos','leéis','leen'],
    indefinido:            ['leí','leíste','leyó','leímos','leísteis','leyeron'],
    imperfecto:            ['leía','leías','leía','leíamos','leíais','leían'],
    perfecto:              ['he leído','has leído','ha leído','hemos leído','habéis leído','han leído'],
    pluscuamperfecto:      ['había leído','habías leído','había leído','habíamos leído','habíais leído','habían leído'],
    futuro:                ['leeré','leerás','leerá','leeremos','leeréis','leerán'],
    condicional:           ['leería','leerías','leería','leeríamos','leeríais','leerían'],
    subjuntivo_presente:   ['lea','leas','lea','leamos','leáis','lean'],
    subjuntivo_imperfecto: ['leyera','leyeras','leyera','leyéramos','leyerais','leyeran'],
    imperativo:            ['—','lee','lea','leamos','leed','lean'],
    imperativo_neg:        ['—','no leas','no lea','no leamos','no leáis','no lean'],
  },

  // ═══ RÉGULIERS -IR ═══════════════════════════════════════════════════════

  vivir: {
    label: 'vivre',
    presente:              ['vivo','vives','vive','vivimos','vivís','viven'],
    indefinido:            ['viví','viviste','vivió','vivimos','vivisteis','vivieron'],
    imperfecto:            ['vivía','vivías','vivía','vivíamos','vivíais','vivían'],
    perfecto:              ['he vivido','has vivido','ha vivido','hemos vivido','habéis vivido','han vivido'],
    pluscuamperfecto:      ['había vivido','habías vivido','había vivido','habíamos vivido','habíais vivido','habían vivido'],
    futuro:                ['viviré','vivirás','vivirá','viviremos','viviréis','vivirán'],
    condicional:           ['viviría','vivirías','viviría','viviríamos','viviríais','vivirían'],
    subjuntivo_presente:   ['viva','vivas','viva','vivamos','viváis','vivan'],
    subjuntivo_imperfecto: ['viviera','vivieras','viviera','viviéramos','vivierais','vivieran'],
    imperativo:            ['—','vive','viva','vivamos','vivid','vivan'],
    imperativo_neg:        ['—','no vivas','no viva','no vivamos','no viváis','no vivan'],
  },
  escribir: {
    label: 'écrire',
    presente:              ['escribo','escribes','escribe','escribimos','escribís','escriben'],
    indefinido:            ['escribí','escribiste','escribió','escribimos','escribisteis','escribieron'],
    imperfecto:            ['escribía','escribías','escribía','escribíamos','escribíais','escribían'],
    perfecto:              ['he escrito','has escrito','ha escrito','hemos escrito','habéis escrito','han escrito'],
    pluscuamperfecto:      ['había escrito','habías escrito','había escrito','habíamos escrito','habíais escrito','habían escrito'],
    futuro:                ['escribiré','escribirás','escribirá','escribiremos','escribiréis','escribirán'],
    condicional:           ['escribiría','escribirías','escribiría','escribiríamos','escribiríais','escribirían'],
    subjuntivo_presente:   ['escriba','escribas','escriba','escribamos','escribáis','escriban'],
    subjuntivo_imperfecto: ['escribiera','escribieras','escribiera','escribiéramos','escribierais','escribieran'],
    imperativo:            ['—','escribe','escriba','escribamos','escribid','escriban'],
    imperativo_neg:        ['—','no escribas','no escriba','no escribamos','no escribáis','no escriban'],
  },
  abrir: {
    label: 'ouvrir',
    presente:              ['abro','abres','abre','abrimos','abrís','abren'],
    indefinido:            ['abrí','abriste','abrió','abrimos','abristeis','abrieron'],
    imperfecto:            ['abría','abrías','abría','abríamos','abríais','abrían'],
    perfecto:              ['he abierto','has abierto','ha abierto','hemos abierto','habéis abierto','han abierto'],
    pluscuamperfecto:      ['había abierto','habías abierto','había abierto','habíamos abierto','habíais abierto','habían abierto'],
    futuro:                ['abriré','abrirás','abrirá','abriremos','abriréis','abrirán'],
    condicional:           ['abriría','abrirías','abriría','abriríamos','abriríais','abrirían'],
    subjuntivo_presente:   ['abra','abras','abra','abramos','abráis','abran'],
    subjuntivo_imperfecto: ['abriera','abrieras','abriera','abriéramos','abrierais','abrieran'],
    imperativo:            ['—','abre','abra','abramos','abrid','abran'],
    imperativo_neg:        ['—','no abras','no abra','no abramos','no abráis','no abran'],
  },

  // ═══ IRRÉGULIERS ═════════════════════════════════════════════════════════

  ser: {
    label: 'être (permanent)',
    presente:              ['soy','eres','es','somos','sois','son'],
    indefinido:            ['fui','fuiste','fue','fuimos','fuisteis','fueron'],
    imperfecto:            ['era','eras','era','éramos','erais','eran'],
    perfecto:              ['he sido','has sido','ha sido','hemos sido','habéis sido','han sido'],
    pluscuamperfecto:      ['había sido','habías sido','había sido','habíamos sido','habíais sido','habían sido'],
    futuro:                ['seré','serás','será','seremos','seréis','serán'],
    condicional:           ['sería','serías','sería','seríamos','seríais','serían'],
    subjuntivo_presente:   ['sea','seas','sea','seamos','seáis','sean'],
    subjuntivo_imperfecto: ['fuera','fueras','fuera','fuéramos','fuerais','fueran'],
    imperativo:            ['—','sé','sea','seamos','sed','sean'],
    imperativo_neg:        ['—','no seas','no sea','no seamos','no seáis','no sean'],
  },
  estar: {
    label: 'être (état/lieu)',
    presente:              ['estoy','estás','está','estamos','estáis','están'],
    indefinido:            ['estuve','estuviste','estuvo','estuvimos','estuvisteis','estuvieron'],
    imperfecto:            ['estaba','estabas','estaba','estábamos','estabais','estaban'],
    perfecto:              ['he estado','has estado','ha estado','hemos estado','habéis estado','han estado'],
    pluscuamperfecto:      ['había estado','habías estado','había estado','habíamos estado','habíais estado','habían estado'],
    futuro:                ['estaré','estarás','estará','estaremos','estaréis','estarán'],
    condicional:           ['estaría','estarías','estaría','estaríamos','estaríais','estarían'],
    subjuntivo_presente:   ['esté','estés','esté','estemos','estéis','estén'],
    subjuntivo_imperfecto: ['estuviera','estuvieras','estuviera','estuviéramos','estuvierais','estuvieran'],
    imperativo:            ['—','está','esté','estemos','estad','estén'],
    imperativo_neg:        ['—','no estés','no esté','no estemos','no estéis','no estén'],
  },
  tener: {
    label: 'avoir',
    presente:              ['tengo','tienes','tiene','tenemos','tenéis','tienen'],
    indefinido:            ['tuve','tuviste','tuvo','tuvimos','tuvisteis','tuvieron'],
    imperfecto:            ['tenía','tenías','tenía','teníamos','teníais','tenían'],
    perfecto:              ['he tenido','has tenido','ha tenido','hemos tenido','habéis tenido','han tenido'],
    pluscuamperfecto:      ['había tenido','habías tenido','había tenido','habíamos tenido','habíais tenido','habían tenido'],
    futuro:                ['tendré','tendrás','tendrá','tendremos','tendréis','tendrán'],
    condicional:           ['tendría','tendrías','tendría','tendríamos','tendríais','tendrían'],
    subjuntivo_presente:   ['tenga','tengas','tenga','tengamos','tengáis','tengan'],
    subjuntivo_imperfecto: ['tuviera','tuvieras','tuviera','tuviéramos','tuvierais','tuvieran'],
    imperativo:            ['—','ten','tenga','tengamos','tened','tengan'],
    imperativo_neg:        ['—','no tengas','no tenga','no tengamos','no tengáis','no tengan'],
  },
  ir: {
    label: 'aller',
    presente:              ['voy','vas','va','vamos','vais','van'],
    indefinido:            ['fui','fuiste','fue','fuimos','fuisteis','fueron'],
    imperfecto:            ['iba','ibas','iba','íbamos','ibais','iban'],
    perfecto:              ['he ido','has ido','ha ido','hemos ido','habéis ido','han ido'],
    pluscuamperfecto:      ['había ido','habías ido','había ido','habíamos ido','habíais ido','habían ido'],
    futuro:                ['iré','irás','irá','iremos','iréis','irán'],
    condicional:           ['iría','irías','iría','iríamos','iríais','irían'],
    subjuntivo_presente:   ['vaya','vayas','vaya','vayamos','vayáis','vayan'],
    subjuntivo_imperfecto: ['fuera','fueras','fuera','fuéramos','fuerais','fueran'],
    imperativo:            ['—','ve','vaya','vayamos','id','vayan'],
    imperativo_neg:        ['—','no vayas','no vaya','no vayamos','no vayáis','no vayan'],
  },
  hacer: {
    label: 'faire',
    presente:              ['hago','haces','hace','hacemos','hacéis','hacen'],
    indefinido:            ['hice','hiciste','hizo','hicimos','hicisteis','hicieron'],
    imperfecto:            ['hacía','hacías','hacía','hacíamos','hacíais','hacían'],
    perfecto:              ['he hecho','has hecho','ha hecho','hemos hecho','habéis hecho','han hecho'],
    pluscuamperfecto:      ['había hecho','habías hecho','había hecho','habíamos hecho','habíais hecho','habían hecho'],
    futuro:                ['haré','harás','hará','haremos','haréis','harán'],
    condicional:           ['haría','harías','haría','haríamos','haríais','harían'],
    subjuntivo_presente:   ['haga','hagas','haga','hagamos','hagáis','hagan'],
    subjuntivo_imperfecto: ['hiciera','hicieras','hiciera','hiciéramos','hicierais','hicieran'],
    imperativo:            ['—','haz','haga','hagamos','haced','hagan'],
    imperativo_neg:        ['—','no hagas','no haga','no hagamos','no hagáis','no hagan'],
  },
  poder: {
    label: 'pouvoir',
    presente:              ['puedo','puedes','puede','podemos','podéis','pueden'],
    indefinido:            ['pude','pudiste','pudo','pudimos','pudisteis','pudieron'],
    imperfecto:            ['podía','podías','podía','podíamos','podíais','podían'],
    perfecto:              ['he podido','has podido','ha podido','hemos podido','habéis podido','han podido'],
    pluscuamperfecto:      ['había podido','habías podido','había podido','habíamos podido','habíais podido','habían podido'],
    futuro:                ['podré','podrás','podrá','podremos','podréis','podrán'],
    condicional:           ['podría','podrías','podría','podríamos','podríais','podrían'],
    subjuntivo_presente:   ['pueda','puedas','pueda','podamos','podáis','puedan'],
    subjuntivo_imperfecto: ['pudiera','pudieras','pudiera','pudiéramos','pudierais','pudieran'],
    imperativo:            ['—','puede','pueda','podamos','poded','puedan'],
    imperativo_neg:        ['—','no puedas','no pueda','no podamos','no podáis','no puedan'],
  },
  querer: {
    label: 'vouloir / aimer',
    presente:              ['quiero','quieres','quiere','queremos','queréis','quieren'],
    indefinido:            ['quise','quisiste','quiso','quisimos','quisisteis','quisieron'],
    imperfecto:            ['quería','querías','quería','queríamos','queríais','querían'],
    perfecto:              ['he querido','has querido','ha querido','hemos querido','habéis querido','han querido'],
    pluscuamperfecto:      ['había querido','habías querido','había querido','habíamos querido','habíais querido','habían querido'],
    futuro:                ['querré','querrás','querrá','querremos','querréis','querrán'],
    condicional:           ['querría','querrías','querría','querríamos','querríais','querrían'],
    subjuntivo_presente:   ['quiera','quieras','quiera','queramos','queráis','quieran'],
    subjuntivo_imperfecto: ['quisiera','quisieras','quisiera','quisiéramos','quisierais','quisieran'],
    imperativo:            ['—','quiere','quiera','queramos','quered','quieran'],
    imperativo_neg:        ['—','no quieras','no quiera','no queramos','no queráis','no quieran'],
  },
  decir: {
    label: 'dire',
    presente:              ['digo','dices','dice','decimos','decís','dicen'],
    indefinido:            ['dije','dijiste','dijo','dijimos','dijisteis','dijeron'],
    imperfecto:            ['decía','decías','decía','decíamos','decíais','decían'],
    perfecto:              ['he dicho','has dicho','ha dicho','hemos dicho','habéis dicho','han dicho'],
    pluscuamperfecto:      ['había dicho','habías dicho','había dicho','habíamos dicho','habíais dicho','habían dicho'],
    futuro:                ['diré','dirás','dirá','diremos','diréis','dirán'],
    condicional:           ['diría','dirías','diría','diríamos','diríais','dirían'],
    subjuntivo_presente:   ['diga','digas','diga','digamos','digáis','digan'],
    subjuntivo_imperfecto: ['dijera','dijeras','dijera','dijéramos','dijerais','dijeran'],
    imperativo:            ['—','di','diga','digamos','decid','digan'],
    imperativo_neg:        ['—','no digas','no diga','no digamos','no digáis','no digan'],
  },
  saber: {
    label: 'savoir',
    presente:              ['sé','sabes','sabe','sabemos','sabéis','saben'],
    indefinido:            ['supe','supiste','supo','supimos','supisteis','supieron'],
    imperfecto:            ['sabía','sabías','sabía','sabíamos','sabíais','sabían'],
    perfecto:              ['he sabido','has sabido','ha sabido','hemos sabido','habéis sabido','han sabido'],
    pluscuamperfecto:      ['había sabido','habías sabido','había sabido','habíamos sabido','habíais sabido','habían sabido'],
    futuro:                ['sabré','sabrás','sabrá','sabremos','sabréis','sabrán'],
    condicional:           ['sabría','sabrías','sabría','sabríamos','sabríais','sabrían'],
    subjuntivo_presente:   ['sepa','sepas','sepa','sepamos','sepáis','sepan'],
    subjuntivo_imperfecto: ['supiera','supieras','supiera','supiéramos','supierais','supieran'],
    imperativo:            ['—','sabe','sepa','sepamos','sabed','sepan'],
    imperativo_neg:        ['—','no sepas','no sepa','no sepamos','no sepáis','no sepan'],
  },
  poner: {
    label: 'mettre / poser',
    presente:              ['pongo','pones','pone','ponemos','ponéis','ponen'],
    indefinido:            ['puse','pusiste','puso','pusimos','pusisteis','pusieron'],
    imperfecto:            ['ponía','ponías','ponía','poníamos','poníais','ponían'],
    perfecto:              ['he puesto','has puesto','ha puesto','hemos puesto','habéis puesto','han puesto'],
    pluscuamperfecto:      ['había puesto','habías puesto','había puesto','habíamos puesto','habíais puesto','habían puesto'],
    futuro:                ['pondré','pondrás','pondrá','pondremos','pondréis','pondrán'],
    condicional:           ['pondría','pondrías','pondría','pondríamos','pondríais','pondrían'],
    subjuntivo_presente:   ['ponga','pongas','ponga','pongamos','pongáis','pongan'],
    subjuntivo_imperfecto: ['pusiera','pusieras','pusiera','pusiéramos','pusierais','pusieran'],
    imperativo:            ['—','pon','ponga','pongamos','poned','pongan'],
    imperativo_neg:        ['—','no pongas','no ponga','no pongamos','no pongáis','no pongan'],
  },
  venir: {
    label: 'venir',
    presente:              ['vengo','vienes','viene','venimos','venís','vienen'],
    indefinido:            ['vine','viniste','vino','vinimos','vinisteis','vinieron'],
    imperfecto:            ['venía','venías','venía','veníamos','veníais','venían'],
    perfecto:              ['he venido','has venido','ha venido','hemos venido','habéis venido','han venido'],
    pluscuamperfecto:      ['había venido','habías venido','había venido','habíamos venido','habíais venido','habían venido'],
    futuro:                ['vendré','vendrás','vendrá','vendremos','vendréis','vendrán'],
    condicional:           ['vendría','vendrías','vendría','vendríamos','vendríais','vendrían'],
    subjuntivo_presente:   ['venga','vengas','venga','vengamos','vengáis','vengan'],
    subjuntivo_imperfecto: ['viniera','vinieras','viniera','viniéramos','vinierais','vinieran'],
    imperativo:            ['—','ven','venga','vengamos','venid','vengan'],
    imperativo_neg:        ['—','no vengas','no venga','no vengamos','no vengáis','no vengan'],
  },
  ver: {
    label: 'voir',
    presente:              ['veo','ves','ve','vemos','veis','ven'],
    indefinido:            ['vi','viste','vio','vimos','visteis','vieron'],
    imperfecto:            ['veía','veías','veía','veíamos','veíais','veían'],
    perfecto:              ['he visto','has visto','ha visto','hemos visto','habéis visto','han visto'],
    pluscuamperfecto:      ['había visto','habías visto','había visto','habíamos visto','habíais visto','habían visto'],
    futuro:                ['veré','verás','verá','veremos','veréis','verán'],
    condicional:           ['vería','verías','vería','veríamos','veríais','verían'],
    subjuntivo_presente:   ['vea','veas','vea','veamos','veáis','vean'],
    subjuntivo_imperfecto: ['viera','vieras','viera','viéramos','vierais','vieran'],
    imperativo:            ['—','ve','vea','veamos','ved','vean'],
    imperativo_neg:        ['—','no veas','no vea','no veamos','no veáis','no vean'],
  },
  dar: {
    label: 'donner',
    presente:              ['doy','das','da','damos','dais','dan'],
    indefinido:            ['di','diste','dio','dimos','disteis','dieron'],
    imperfecto:            ['daba','dabas','daba','dábamos','dabais','daban'],
    perfecto:              ['he dado','has dado','ha dado','hemos dado','habéis dado','han dado'],
    pluscuamperfecto:      ['había dado','habías dado','había dado','habíamos dado','habíais dado','habían dado'],
    futuro:                ['daré','darás','dará','daremos','daréis','darán'],
    condicional:           ['daría','darías','daría','daríamos','daríais','darían'],
    subjuntivo_presente:   ['dé','des','dé','demos','deis','den'],
    subjuntivo_imperfecto: ['diera','dieras','diera','diéramos','dierais','dieran'],
    imperativo:            ['—','da','dé','demos','dad','den'],
    imperativo_neg:        ['—','no des','no dé','no demos','no deis','no den'],
  },
  salir: {
    label: 'sortir',
    presente:              ['salgo','sales','sale','salimos','salís','salen'],
    indefinido:            ['salí','saliste','salió','salimos','salisteis','salieron'],
    imperfecto:            ['salía','salías','salía','salíamos','salíais','salían'],
    perfecto:              ['he salido','has salido','ha salido','hemos salido','habéis salido','han salido'],
    pluscuamperfecto:      ['había salido','habías salido','había salido','habíamos salido','habíais salido','habían salido'],
    futuro:                ['saldré','saldrás','saldrá','saldremos','saldréis','saldrán'],
    condicional:           ['saldría','saldrías','saldría','saldríamos','saldríais','saldrían'],
    subjuntivo_presente:   ['salga','salgas','salga','salgamos','salgáis','salgan'],
    subjuntivo_imperfecto: ['saliera','salieras','saliera','saliéramos','salierais','salieran'],
    imperativo:            ['—','sal','salga','salgamos','salid','salgan'],
    imperativo_neg:        ['—','no salgas','no salga','no salgamos','no salgáis','no salgan'],
  },
  dormir: {
    label: 'dormir',
    presente:              ['duermo','duermes','duerme','dormimos','dormís','duermen'],
    indefinido:            ['dormí','dormiste','durmió','dormimos','dormisteis','durmieron'],
    imperfecto:            ['dormía','dormías','dormía','dormíamos','dormíais','dormían'],
    perfecto:              ['he dormido','has dormido','ha dormido','hemos dormido','habéis dormido','han dormido'],
    pluscuamperfecto:      ['había dormido','habías dormido','había dormido','habíamos dormido','habíais dormido','habían dormido'],
    futuro:                ['dormiré','dormirás','dormirá','dormiremos','dormiréis','dormirán'],
    condicional:           ['dormiría','dormirías','dormiría','dormiríamos','dormiríais','dormirían'],
    subjuntivo_presente:   ['duerma','duermas','duerma','durmamos','durmáis','duerman'],
    subjuntivo_imperfecto: ['durmiera','durmieras','durmiera','durmiéramos','durmierais','durmieran'],
    imperativo:            ['—','duerme','duerma','durmamos','dormid','duerman'],
    imperativo_neg:        ['—','no duermas','no duerma','no durmamos','no durmáis','no duerman'],
  },
  jugar: {
    label: 'jouer',
    presente:              ['juego','juegas','juega','jugamos','jugáis','juegan'],
    indefinido:            ['jugué','jugaste','jugó','jugamos','jugasteis','jugaron'],
    imperfecto:            ['jugaba','jugabas','jugaba','jugábamos','jugabais','jugaban'],
    perfecto:              ['he jugado','has jugado','ha jugado','hemos jugado','habéis jugado','han jugado'],
    pluscuamperfecto:      ['había jugado','habías jugado','había jugado','habíamos jugado','habíais jugado','habían jugado'],
    futuro:                ['jugaré','jugarás','jugará','jugaremos','jugaréis','jugarán'],
    condicional:           ['jugaría','jugarías','jugaría','jugaríamos','jugaríais','jugarían'],
    subjuntivo_presente:   ['juegue','juegues','juegue','juguemos','juguéis','jueguen'],
    subjuntivo_imperfecto: ['jugara','jugaras','jugara','jugáramos','jugarais','jugaran'],
    imperativo:            ['—','juega','juegue','juguemos','jugad','jueguen'],
    imperativo_neg:        ['—','no juegues','no juegue','no juguemos','no juguéis','no jueguen'],
  },
  pensar: {
    label: 'penser',
    presente:              ['pienso','piensas','piensa','pensamos','pensáis','piensan'],
    indefinido:            ['pensé','pensaste','pensó','pensamos','pensasteis','pensaron'],
    imperfecto:            ['pensaba','pensabas','pensaba','pensábamos','pensabais','pensaban'],
    perfecto:              ['he pensado','has pensado','ha pensado','hemos pensado','habéis pensado','han pensado'],
    pluscuamperfecto:      ['había pensado','habías pensado','había pensado','habíamos pensado','habíais pensado','habían pensado'],
    futuro:                ['pensaré','pensarás','pensará','pensaremos','pensaréis','pensarán'],
    condicional:           ['pensaría','pensarías','pensaría','pensaríamos','pensaríais','pensarían'],
    subjuntivo_presente:   ['piense','pienses','piense','pensemos','penséis','piensen'],
    subjuntivo_imperfecto: ['pensara','pensaras','pensara','pensáramos','pensarais','pensaran'],
    imperativo:            ['—','piensa','piense','pensemos','pensad','piensen'],
    imperativo_neg:        ['—','no pienses','no piense','no pensemos','no penséis','no piensen'],
  },
  volver: {
    label: 'retourner / revenir',
    presente:              ['vuelvo','vuelves','vuelve','volvemos','volvéis','vuelven'],
    indefinido:            ['volví','volviste','volvió','volvimos','volvisteis','volvieron'],
    imperfecto:            ['volvía','volvías','volvía','volvíamos','volvíais','volvían'],
    perfecto:              ['he vuelto','has vuelto','ha vuelto','hemos vuelto','habéis vuelto','han vuelto'],
    pluscuamperfecto:      ['había vuelto','habías vuelto','había vuelto','habíamos vuelto','habíais vuelto','habían vuelto'],
    futuro:                ['volveré','volverás','volverá','volveremos','volveréis','volverán'],
    condicional:           ['volvería','volverías','volvería','volveríamos','volveríais','volverían'],
    subjuntivo_presente:   ['vuelva','vuelvas','vuelva','volvamos','volváis','vuelvan'],
    subjuntivo_imperfecto: ['volviera','volvieras','volviera','volviéramos','volvierais','volvieran'],
    imperativo:            ['—','vuelve','vuelva','volvamos','volved','vuelvan'],
    imperativo_neg:        ['—','no vuelvas','no vuelva','no volvamos','no volváis','no vuelvan'],
  },
};

// ─── GENERATE CARDS FROM VERBS ───────────────────────────────────────────────
// Note: pour l'impératif, yo (index 0) = '—', pas de carte générée
function generateCards() {
  const cards = [];
  let id = 1;
  for (const [verb, data] of Object.entries(VERBS)) {
    // Générer le subjonctif passé depuis le participe passé (extrait du perfecto)
    // "he hablado" → "hablado"
    const participio = data.perfecto ? data.perfecto[0].split(' ')[1] : null;
    if (participio) {
      data.subjuntivo_pasado = HABER_SUBJ.map(aux => `${aux} ${participio}`);
    }

    for (const [tense, forms] of Object.entries(data)) {
      if (tense === 'label') continue;
      const isImperativo = tense === 'imperativo' || tense === 'imperativo_neg';
      forms.forEach((answer, i) => {
        if (answer === '—') return;
        if (isImperativo && i === 0) return;
        cards.push({
          id: id++,
          verb,
          verbLabel: data.label,
          tense,
          tenseLabel: TENSE_LABELS[tense] || tense,
          pronoun: PRONOUNS[i],
          answer,
        });
      });
    }
  }
  return cards;
}

const ALL_CARDS = generateCards();
